apiRules:
  - exclude:
      uidRegex: ^System\.
      type: Namespace
  - exclude:
      uidRegex: ^Microsoft\.
      type: Namespace
  - exclude:
      uidRegex: \.Program$
      type: Type
  - exclude:
      uidRegex: \.Startup$
      type: Type
  - include:
      uidRegex: ^EchoHub\.
      type: Namespace
  - include:
      uidRegex: ^EchoHub\.
      type: Type
